version: "3.8"

services:

  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    image: ssed-python
    environment:
      - OPENAI_API_KEY
    volumes:
      - ".:/ssed"
    ports:
      - "8000:8000"
    command: /scripts/run-api.sh