version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: ssed-backend
    environment:
      - OPENAI_API_KEY
      - DATA_SOURCE=/data/awards
    volumes:
      - "./backend:/ssed"
    ports:
      - "8000:8000"
    command: /scripts/run-api.sh

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: ssed-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - "./frontend:/ssed"
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend