import '../styles/globals.css';

import Header from '../components/Header';
import Input from '../components/Input';


export const metadata = {
  title: 'Semantic Search',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Input />
        {children}
      </body>
    </html>
  )
}
