import '../styles/globals.css';

import Header from '../components/Header';


export const metadata = {
  title: 'Semantic Search',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href="/favicon.ico"></link>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
